apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.services.port }}
    targetPort: {{ .Values.services.targetPort }}
    protocol: {{ .Values.services.protocol }}
  type: {{ .Values.services.type }}